spring.application.name=api-gateway
server.port=0

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Api-gateway logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# Product service public endpoints through
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/products/get/**



